ТЗ 13. Классы Item и User
Ekaterina-Kirpi/java-shareit pull request #1
Opened 2023-06-25 15:09 UTC by Ekaterina-Kirpi

Созданы классы  Item и User, реализованы хранилища и сервер с Dto, контроллеры.

2023-06-26 08:51 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которое надо исправить!

Желаю удачи!

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        return !users.containsKey(id);
Можно обойтись без лишних проверок:

```java
return users.remove(userId) != null;
```

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        return users.get(userUp.getId());
Это лишние взаимодействия с коллекцией.

Можно просто:
 ```java
 return userUp;
 ```

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        return users.get(user.getId());
можно не делать этот лишний `get`, а просто сделать:

```java
return user;
```

Это не слишком важно, когда мы храним данные в оперативной памяти, но если мы записываем их в файл или СУБД, то надо всегда стараться минимизировать число лишних обращений к файловой системе или СУБД.

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        return items.get(item.getId());
```java
return item;
```

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                .filter(i -> Objects.equals(i.getOwner().getId(), userId))
несмотря на то, что это лямбда выражение, переменные стоит именовать полноценно, тем более, что здесь не используется слово `item`

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                .filter(i -> i.getDescription().toLowerCase().contains(text.toLowerCase()) && i.getAvailable())
А если текст содержится в названии, а не в описании?

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            throw new NotFoundException("Вещь с id: " + itemStorage.getById(item.getId()) + " не найдена");
По возможности дважды лучше не обращаться к хранилищу, а просто сохранить результат в переменную

2023-06-26 08:51 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        } else {
Нет необходимости в `else`

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        return !users.containsKey(id);
Спасибо!) исправила

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        return users.get(userUp.getId());
Исправлено

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        return users.get(user.getId());
Учла, спасибо!

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        return items.get(item.getId());
Исправила.

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                .filter(i -> Objects.equals(i.getOwner().getId(), userId))
Исправила

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +                .filter(i -> i.getDescription().toLowerCase().contains(text.toLowerCase()) && i.getAvailable())
Возможно) Добавила поиск и в названии

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +            throw new NotFoundException("Вещь с id: " + itemStorage.getById(item.getId()) + " не найдена");
Сохранила в переменную

2023-06-26 22:06 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        } else {
+

2023-06-27 12:51 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-07-12 10:14 UTC, Ekaterina-Kirpi commented
Спасибо!)

2023-07-12 10:14 UTC, merged