Тз 14
Ekaterina-Kirpi/java-shareit pull request #2
Opened 2023-07-15 12:57 UTC by Ekaterina-Kirpi

Добавлена функция бронирования. Класс Booking, хранилище, сервер с Dto, контроллер. Так же переделаны хранилища для Item и User

2023-07-16 18:41 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-07-16 18:41 UTC, LexLippi commented on src/main/resources/schema.sql
> +                                        end_booking TIMESTAMP WITHOUT TIME ZONE
эти поля могут быть `null`?

2023-07-16 18:41 UTC, LexLippi commented on src/main/resources/schema.sql
> +                                        created TIMESTAMP WITH TIME ZONE
могут быть `null`?

2023-07-16 18:41 UTC, LexLippi commented on src/main/resources/data.sql
> +ALTER TABLE ITEMS ALTER COLUMN ID RESTART WITH 1;
По возможности стоит избегать таких скриптов. 
Представь, что на выходе получаем реаьлное продакшен-приложение. Долго им будут пользоваться люди, если при каждом обновлении все их данные будут удалены?

2023-07-16 18:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    @Transactional(readOnly = true)
Эту аннотацию можно повесить на класс

2023-07-16 18:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public UserDto createUser(UserDto userDto) {
Почему здесь нет `Transactional`

2023-07-16 18:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public void deleteUser(Long userId) {
А тут не надо `Transactional`?

2023-07-16 18:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(nullable = false, length = 500, unique = true)
а почему длина здесь и в СУБД не совпадает?

2023-07-16 18:41 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>      public ItemDto createItem(ItemDto itemDto, Long userId) {
`Transactional`?

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/resources/schema.sql
> +                                        end_booking TIMESTAMP WITHOUT TIME ZONE
Нет. поправила

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/resources/schema.sql
> +                                        created TIMESTAMP WITH TIME ZONE
+

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/resources/data.sql
> +ALTER TABLE ITEMS ALTER COLUMN ID RESTART WITH 1;
Спасибо

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    @Transactional(readOnly = true)
Сделала на класс

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public UserDto createUser(UserDto userDto) {
+

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    public void deleteUser(Long userId) {
+

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(nullable = false, length = 500, unique = true)
+

2023-07-17 08:46 UTC, Ekaterina-Kirpi commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
>      public ItemDto createItem(ItemDto itemDto, Long userId) {
+

2023-07-18 07:00 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-07-18 07:17 UTC, Ekaterina-Kirpi commented
Спасибо!

2023-07-18 09:38 UTC, merged