ТЗ 16 Add docker
Ekaterina-Kirpi/java-shareit pull request #4
Opened 2023-08-10 11:37 UTC by Ekaterina-Kirpi

2023-08-11 07:41 UTC, LexLippi requested changes
Привет!

Замечательная работа!

Есть пара небольших замечаний, которые необходимо исправить!

Желаю удачи!

2023-08-11 07:41 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/State.java
> +        return UNSUPPORTED_STATUS;
С точки зрения созжания статуса из строки, передача не существующего статуса - это исключительное событие, поэтому можно и нужно, выбросить исключение.

А иначе выполнение кода будет происходить в обычном режиме, и возможно ошибка во внешнем сервисе никогда не будет исправлена, а просто будет выставляться некорректный статус

2023-08-11 07:41 UTC, LexLippi commented on server/src/main/java/ru/practicum/shareit/ShareItApp.java
> +//}
Зачем нужен этот класс?
Стоит его удалить, если он не нужен

2023-08-11 07:41 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +            @PathVariable @Min(1) Long requestId) {
А почему здесь `Min`, а не `Positive`?
В большинстве случаев используешь `Positive`

2023-08-11 07:41 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestParam(value = "from", defaultValue = "0") @PositiveOrZero Integer from,
`value` и название переменной не отличаются, тогда непонятно зачем дублировать эту инфу

2023-08-11 09:05 UTC, Ekaterina-Kirpi commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestParam(value = "from", defaultValue = "0") @PositiveOrZero Integer from,
Привет! Решила оставить, если ты не против.
Чтобы было понятней)) какой параметр и какое его значение используется в данном случае.
Все остальные замечания исправлены!

2023-08-11 09:05 UTC, Ekaterina-Kirpi commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +            @PathVariable @Min(1) Long requestId) {
+

2023-08-11 09:05 UTC, Ekaterina-Kirpi commented on server/src/main/java/ru/practicum/shareit/ShareItApp.java
> +//}
+

2023-08-11 09:05 UTC, Ekaterina-Kirpi commented on gateway/src/main/java/ru/practicum/shareit/booking/State.java
> +        return UNSUPPORTED_STATUS;
+

2023-08-12 08:31 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-08-14 06:56 UTC, merged